### ISSUE TITLE
Exporter throwing 500

### ISSUE THREAD

**Issue by CreedsCode** [arunvelsriram/sftp-exporter#3]
Hi,
I use the sftp-exporter to monitor a managed FTP server. The scrape interval in Prometheus is set to 24H.
Every scrape on Prometheus displays this following message: 
_"Get "http://sftp-basic-exporter:8081/metrics": dial tcp 172.21.0.2:8081: connect: connection refused"_

After some digging I could't make sense what could possible go wrong.

Logs:
> time="2022-02-04T14:51:41Z" level=debug msg="connected to SFTP"
time="2022-02-04T14:51:41Z" level=debug msg="collecting filesystem metrics"
time="2022-02-04T14:51:41Z" level=debug msg="collecting filesystem metrics for path: ./"
time="2022-02-04T14:51:41Z" level=debug msg="writing filesystem metrics for path: ./"
time="2022-02-04T14:51:41Z" level=debug msg="collecting object metrics"
time="2022-02-04T14:51:41Z" level=debug msg="collecting object metrics for path: ./"
time="2022-02-05T03:27:31Z" level=error msg="failed to send packet: EOF" path=./ when="collecting object metrics"
time="2022-02-05T03:27:31Z" level=error msg="close tcp 172.21.0.2:56578-> XXX.XXX.XXX.XX:22: use of closed network connection" when="closing SSH connection"
2022/02/05 03:27:31 http: superfluous response.WriteHeader call from github.com/arunvelsriram/sftp-exporter/pkg/server.(*loggingResponseWriter).WriteHeader (logging_middleware.go:28)
time="2022-02-05T03:27:31Z" level=info msg="request completed" duration=12h38m58.35611428s method=GET size=4096 status=500 uri=/metrics
2022/02/05 03:27:31 http: superfluous response.WriteHeader call from github.com/arunvelsriram/sftp-exporter/pkg/server.(*loggingResponseWriter).WriteHeader (logging_middleware.go:28)
time="2022-02-05T03:27:31Z" level=info msg="request completed" duration=12h35m49.991883048s method=GET size=4096 status=500 uri=/metrics
time="2022-02-05T03:27:44Z" level=error msg=EOF when="closing SFTP connection"
2022/02/05 03:27:44 http: superfluous response.WriteHeader call from github.com/arunvelsriram/sftp-exporter/pkg/server.(*loggingResponseWriter).WriteHeader (logging_middleware.go:28)
time="2022-02-05T03:27:44Z" level=info msg="request completed" duration=12h37m56.92274825s method=GET size=4096 status=500 uri=/metrics

**Comment by arunvelsriram** [comment]
Am not sure if it will work with FTP server. could you check if you are able to connect to the server using sftp client?

**Comment by arunvelsriram** [comment]
Close as its stale
