### ISSUE TITLE
Cant access sftp metrics in browser

### ISSUE THREAD

**Issue by guptaashim01** [arunvelsriram/sftp-exporter#5]
Hi,

I ran the sftp exporter in docker on my machine. Logs show its starting up  but when i try to access the metrics in browser , it says cant reach this page.

time="2023-07-20T07:37:04Z" level=debug msg="All configs:"
time="2023-07-20T07:37:04Z" level=debug msg="port: 8085"
time="2023-07-20T07:37:04Z" level=debug msg="config-file: sftp-exporter.yaml"
time="2023-07-20T07:37:04Z" level=debug msg="sftp-paths: /monitor"
time="2023-07-20T07:37:04Z" level=debug msg="sftp-password: **********"
time="2023-07-20T07:37:04Z" level=debug msg="bind-address: localhost"
time="2023-07-20T07:37:04Z" level=debug msg="sftp-key-passphrase: **********"
time="2023-07-20T07:37:04Z" level=debug msg="sftp-user: xyz"
time="2023-07-20T07:37:04Z" level=debug msg="sftp-key: **********"
time="2023-07-20T07:37:04Z" level=debug msg="sftp-host: 1.2.3.4"
time="2023-07-20T07:37:04Z" level=debug msg="log-level: trace"
time="2023-07-20T07:37:04Z" level=debug msg="sftp-port: 22"
time="2023-07-20T07:37:04Z" level=info msg="Server will be listening on: localhost:8085"

**Comment by arunvelsriram** [comment]
Hi @guptaashim01. Could you share the docker command that you used and the output of `docker ps` command?

**Comment by guptaashim01** [comment]
Hi Arun,

Below is the docker command
**************************************
docker run -p 8085:8080 --mount type=bind,source=%cd%/sftp-exporter.yaml,target=/sftp-exporter/sftp-exporter.yaml sftp-exporter

Output of docker ps command
**************************************

CONTAINER ID   IMAGE           COMMAND             CREATED          STATUS          PORTS                                       NAMES
bcea4838ee02   sftp-exporter   "./sftp-exporter"   44 seconds ago   Up 43 seconds   0.0.0.0:8085->8080/tcp, :::8085->8080/tcp   mystifying_williamson


Thanks
Ashim

**Comment by arunvelsriram** [comment]
I see in the server logs `time="2023-07-20T07:37:04Z" level=info msg="Server will be listening on: localhost:8085"` which means sftp exporter is running on port `8085`. 

However, in your docker command the port publish spec has `8085:8080`. Since there is no service running on port `8080` you are not able to reach the exporter endpoints

**Comment by guptaashim01** [comment]
Hi Arun,

I tried to run below command but still the issue is same

docker run -p 8080:8080 --mount type=bind,source=%cd%/sftp-exporter.yaml,target=/sftp-exporter/sftp-exporter.yaml sftp-exporter

Thanks
Ashim

**Comment by guptaashim01** [comment]
I just ran below command and i am able to access the url  for this app

docker run -d -p 80:80 docker/getting-started 

After this i ran another command but still the same issue.I see sftp-exporter is running in docker desktop but i am not able to access the url

docker run -d  -p 90:90 --mount type=bind,source=%cd%/sftp-exporter.yaml,target=/sftp-exporter/sftp-exporter.yaml sftp-exporter

**Comment by arunvelsriram** [comment]
Not sure why you are trying with various different ports. To keep things simple, just start with the default configuration and do a port forwarding from any desired port on your host machine to the default sftp-exporter port (8080) inside the container.

> Strange thing is if i mention incorrect sftp servname logs still show the same that it started successfully

Thats expected. In case the exporter is not able to connect to the SFTP then it sends `up` metric as `0`.

**Comment by arunvelsriram** [comment]
Closing this as doesn't seem to be an issue with sftp-exporter itself
